# Generated by Django 5.0.1 on 2024-02-29 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_diagnosishistory_patient_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosishistory',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosis.appointment'),
        ),
    ]
