# Generated by Django 5.0.1 on 2024-03-01 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0008_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_requests', to='diagnosis.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=3)),
                ('age', models.PositiveIntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DonorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.doctorrequest')),
                ('donor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.donorprofile')),
            ],
        ),
    ]
