# Generated by Django 5.0.1 on 2024-03-01 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0009_doctorrequest_donorprofile_donorrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosishistory',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosis.appointment'),
        ),
    ]
